### ISSUE TITLE
Issue while fetching react hooks via named export , import React , {useState} from 'react' ,  throwing's error

### ISSUE THREAD

**Issue by anilrupela** [piral-samples/piral-cloud-native-federation-demo#1]
In example at all other places, hooks are not imported via named export, instead directly used like React.useState and it works fine.

like in mf-red/src/product-page.tsx

But when i tried importing directly like below, it failed during runtime 

import React , {useState} from "react";

Uncaught (in promise) SyntaxError: The requested module 'blob:
http://localhost:xxx/1b2bd859-cb42-4c0f-9abc-f62911ec2609
' does not provide an export named 'useState'

Please suggest, if this is a valid or not,or any solution for this as third part depdency uses like this

**Comment by FlorianRappl** [comment]
Sorry I cannot really help you on this one as the question is tightly bound to native federation / how the build adapter works. So any inquiry on this should be placed to native federation people.

What I can tell you is that React should be used *exactly* as shown in the example. As React is used as an ESM (but originally it's not - its a CJS) it behaves bundler specific. In case of the shown configuration you'll have essentially just the default export - nothing else. So just use the default export.

The assumption that you make is that it behaves as the original CJS, which has a star export (and not a default export) - thus things like `useState` can be imported directly. This would only work of the ES interop is active - providing the star export as a decomposition from the default export. As mentioned, in the configuration this is not the case.

In Piral, as an example, we automatically patch this (so ES interop is active). Here, using just plain native federation / the given build adapter, it is not patched and you have to deal with the shown behavior.

Hope that helps!
